services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "33066:3306"
#    volumes:
#      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "mysql://afyakaar:Busboy8_Synopses_Scoured@db:3306/afyakaar"
      PORT: "3001"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend

  backoffice:
    build: ./backoffice
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  uploads_data:
